baseURL = "https://sambyte.net/systology/"
languageCode = "en-us"
title = "Systology"
enableGitInfo = true
taxonomies = { tag = "tags", category = "categories" }

# Useful links to learn more about tweaking code blocks:
# https://gohugo.io/configuration/markup/
# https://gohugo.io/quick-reference/syntax-highlighting-styles/
[markup]
  [markup.highlight]
    noClasses = false
    noBackground = true
    lineNos = false
    style = "modus-vivendi"
